using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;

namespace DnsClientX {
    /// <summary>
    /// Partial <see cref="ClientX"/> class containing reusable request-based DNS query execution.
    /// </summary>
    public partial class ClientX {
        internal static Func<ResolveDnsRequest, string[], DnsRecordType, CancellationToken, Task<DnsResponse[]>>? QueryDnsRequestOverride;

        /// <summary>
        /// Executes a DNS query request that can target single resolvers, explicit servers, or the multi-resolver.
        /// </summary>
        /// <param name="request">The reusable DNS query request.</param>
        /// <param name="cancellationToken">Token used to cancel the operation.</param>
        /// <returns>A task producing all responses generated by the request.</returns>
        public static Task<DnsResponse[]> QueryDns(ResolveDnsRequest request, CancellationToken cancellationToken = default) {
            if (request == null) {
                throw new ArgumentNullException(nameof(request));
            }

            return QueryDnsInternal(request, cancellationToken);
        }

        /// <summary>
        /// Executes a DNS query request synchronously.
        /// </summary>
        /// <param name="request">The reusable DNS query request.</param>
        /// <param name="cancellationToken">Token used to cancel the operation.</param>
        /// <returns>The responses generated by the request.</returns>
        public static DnsResponse[] QueryDnsSync(ResolveDnsRequest request, CancellationToken cancellationToken = default) {
            return QueryDns(request, cancellationToken).RunSync(cancellationToken);
        }

        private static async Task<DnsResponse[]> QueryDnsInternal(ResolveDnsRequest request, CancellationToken cancellationToken) {
            request.Validate();

            string[] namesToUse = request.GetExpandedNames();
            var ednsOptions = request.CreateEdnsOptions();

            if (request.IsMultiResolverRequest) {
                return await ExecuteMultiResolverAsync(request, namesToUse, ednsOptions, cancellationToken).ConfigureAwait(false);
            }

            if (request.Servers.Length > 0) {
                return await ExecuteServerAsync(request, namesToUse, ednsOptions, cancellationToken).ConfigureAwait(false);
            }

            return await ExecuteProviderAsync(request, namesToUse, ednsOptions, cancellationToken).ConfigureAwait(false);
        }

        private static async Task<DnsResponse[]> ExecuteMultiResolverAsync(ResolveDnsRequest request, string[] namesToUse, EdnsOptions? ednsOptions, CancellationToken cancellationToken) {
            DnsResolverEndpoint[] endpoints = ExpandMultiResolverEndpoints(request);
            if (endpoints.Length == 0) {
                throw new InvalidOperationException("No endpoints were produced from the specified resolver inputs.");
            }

            var options = new MultiResolverOptions {
                Strategy = request.ResolverStrategy,
                MaxParallelism = Math.Max(1, request.MaxParallelism),
                RespectEndpointTimeout = request.RespectEndpointTimeout,
                DefaultTimeout = TimeSpan.FromMilliseconds(request.TimeOutMilliseconds),
                FastestCacheDuration = TimeSpan.FromMinutes(Math.Max(1, request.FastestCacheMinutes)),
                PerEndpointMaxInFlight = request.PerEndpointMaxInFlight > 0 ? request.PerEndpointMaxInFlight : null,
                EnableResponseCache = request.ResponseCache,
                CacheExpiration = request.CacheExpirationSeconds > 0 ? TimeSpan.FromSeconds(request.CacheExpirationSeconds) : null,
                MinCacheTtl = request.MinCacheTtlSeconds > 0 ? TimeSpan.FromSeconds(request.MinCacheTtlSeconds) : null,
                MaxCacheTtl = request.MaxCacheTtlSeconds > 0 ? TimeSpan.FromSeconds(request.MaxCacheTtlSeconds) : null,
                RequestDnsSec = request.ShouldRequestDnsSec,
                ValidateDnsSec = request.ShouldValidateDnsSec,
                TypedRecords = request.TypedRecords,
                ParseTypedTxtRecords = request.ParseTypedTxtRecords,
                CheckingDisabled = request.CheckingDisabled,
                EdnsOptions = ednsOptions,
                UserAgent = request.UserAgent,
                HttpVersion = request.HttpVersion,
                IgnoreCertificateErrors = request.IgnoreCertificateErrors,
                UseTcpFallback = request.UseTcpFallback,
                WebProxy = request.CreateWebProxy(),
                MaxConnectionsPerServer = request.EffectiveMaxConnectionsPerServer,
                MaxConcurrency = request.EffectiveMaxConcurrency
            };

            using var resolver = new DnsMultiResolver(endpoints, options);
            var responses = new List<DnsResponse>();
            foreach (var recordType in request.RecordTypes) {
                var result = await ExecuteWithRetryAsync(
                    request,
                    () => resolver.QueryBatchAsync(namesToUse, recordType, cancellationToken),
                    cancellationToken).ConfigureAwait(false);
                responses.AddRange(result);
            }

            return responses.ToArray();
        }

        private static async Task<DnsResponse[]> ExecuteServerAsync(ResolveDnsRequest request, string[] namesToUse, EdnsOptions? ednsOptions, CancellationToken cancellationToken) {
            List<string> serverOrder = GetValidatedServers(request);
            if (request.RandomServer) {
                Shuffle(serverOrder);
            }

            if (request.AllServers && request.Fallback && !request.RandomServer) {
                Shuffle(serverOrder);
            }

            IEnumerable<DnsResponse> responses;
            if (request.AllServers) {
                var aggregated = new List<DnsResponse>();
                foreach (string serverName in serverOrder) {
                    aggregated.AddRange(await ExecuteWithRetryAsync(request, async () => {
                        using var client = CreateClientForServer(request, serverName, ednsOptions);
                        return await QueryWithRequestAsync(client, request, namesToUse, cancellationToken).ConfigureAwait(false);
                    }, cancellationToken).ConfigureAwait(false));
                }

                responses = aggregated;
            } else if (request.Fallback) {
                var aggregated = new List<DnsResponse>();
                foreach (string serverName in serverOrder) {
                    var result = await ExecuteWithRetryAsync(request, async () => {
                        using var client = CreateClientForServer(request, serverName, ednsOptions);
                        return await QueryWithRequestAsync(client, request, namesToUse, cancellationToken).ConfigureAwait(false);
                    }, cancellationToken).ConfigureAwait(false);
                    aggregated.AddRange(result);
                    if (aggregated.Any(r => r.Status == DnsResponseCode.NoError)) {
                        break;
                    }
                }

                responses = aggregated;
            } else {
                string serverName = serverOrder[0];
                responses = await ExecuteWithRetryAsync(request, async () => {
                    using var client = CreateClientForServer(request, serverName, ednsOptions);
                    return await QueryWithRequestAsync(client, request, namesToUse, cancellationToken).ConfigureAwait(false);
                }, cancellationToken).ConfigureAwait(false);
            }

            return responses.ToArray();
        }

        private static async Task<DnsResponse[]> ExecuteProviderAsync(ResolveDnsRequest request, string[] namesToUse, EdnsOptions? ednsOptions, CancellationToken cancellationToken) {
            DnsEndpoint provider = request.DnsProviders.Length == 0 ? DnsEndpoint.System : request.DnsProviders[0];
            if (provider == DnsEndpoint.RootServer) {
                return await ExecuteWithRetryAsync(request, async () => {
                    var responses = new List<DnsResponse>();
                    foreach (var recordType in request.RecordTypes) {
                        var result = await QueryDns(
                            namesToUse,
                            recordType,
                            provider,
                            request.DnsSelectionStrategy,
                            request.TimeOutMilliseconds,
                            retryOnTransient: false,
                            maxRetries: 1,
                            request.RetryDelayMs,
                            request.ShouldRequestDnsSec,
                            request.ShouldValidateDnsSec,
                            request.TypedRecords,
                            request.ParseTypedTxtRecords,
                            cancellationToken).ConfigureAwait(false);
                        responses.AddRange(result);
                    }

                    return responses.ToArray();
                }, cancellationToken).ConfigureAwait(false);
            }

            return await ExecuteWithRetryAsync(request, async () => {
                using var client = CreateClientForProvider(request, provider, ednsOptions);
                return await QueryWithRequestAsync(client, request, namesToUse, cancellationToken).ConfigureAwait(false);
            }, cancellationToken).ConfigureAwait(false);
        }

        private static async Task<DnsResponse[]> QueryWithRequestAsync(ClientX client, ResolveDnsRequest request, string[] namesToUse, CancellationToken cancellationToken) {
            var overrideHandler = QueryDnsRequestOverride;
            if (overrideHandler != null) {
                var overridden = new List<DnsResponse>();
                foreach (var recordType in request.RecordTypes) {
                    overridden.AddRange(await overrideHandler(request, namesToUse, recordType, cancellationToken).ConfigureAwait(false));
                }

                return overridden.ToArray();
            }

            var responses = new List<DnsResponse>();
            foreach (var recordType in request.RecordTypes) {
                var result = await client.Resolve(
                    namesToUse,
                    recordType,
                    requestDnsSec: request.ShouldRequestDnsSec,
                    validateDnsSec: request.ShouldValidateDnsSec,
                    returnAllTypes: false,
                    retryOnTransient: false,
                    maxRetries: 1,
                    retryDelayMs: request.RetryDelayMs,
                    typedRecords: request.TypedRecords,
                    parseTypedTxtRecords: request.ParseTypedTxtRecords,
                    cancellationToken: cancellationToken).ConfigureAwait(false);
                responses.AddRange(result);
            }

            return responses.ToArray();
        }

        private static async Task<DnsResponse[]> ExecuteWithRetryAsync(ResolveDnsRequest request, Func<Task<DnsResponse[]>> query, CancellationToken cancellationToken) {
            DnsResponse[] lastResults = Array.Empty<DnsResponse>();
            Exception? lastException = null;

            for (int attempt = 1; attempt <= request.RetryCount; attempt++) {
                cancellationToken.ThrowIfCancellationRequested();

                try {
                    lastResults = await query().ConfigureAwait(false);
                    if (!lastResults.Any(DnsQueryDiagnostics.IsTransient)) {
                        return lastResults;
                    }
                } catch (Exception ex) when (DnsQueryDiagnostics.IsTransient(ex)) {
                    lastException = ex;
                }

                if (attempt < request.RetryCount) {
                    await Task.Delay(request.RetryDelayMs, cancellationToken).ConfigureAwait(false);
                }
            }

            if (lastException != null) {
                throw lastException;
            }

            return lastResults;
        }

        private static ClientX CreateClientForServer(ResolveDnsRequest request, string serverName, EdnsOptions? ednsOptions) {
            ClientX client;
            if (UsesExplicitServerBaseUri(request.RequestFormat)) {
                client = new ClientX(
                    CreateServerBaseUri(serverName, request.RequestFormat, request.Port),
                    request.RequestFormat,
                    timeOutMilliseconds: request.TimeOutMilliseconds,
                    userAgent: request.UserAgent,
                    httpVersion: request.HttpVersion,
                    ignoreCertificateErrors: request.IgnoreCertificateErrors,
                    enableCache: false,
                    useTcpFallback: request.UseTcpFallback,
                    webProxy: request.CreateWebProxy(),
                    maxConnectionsPerServer: request.EffectiveMaxConnectionsPerServer);
            } else {
                client = new ClientX(
                    serverName,
                    request.RequestFormat,
                    timeOutMilliseconds: request.TimeOutMilliseconds,
                    userAgent: request.UserAgent,
                    httpVersion: request.HttpVersion,
                    ignoreCertificateErrors: request.IgnoreCertificateErrors,
                    enableCache: false,
                    useTcpFallback: request.UseTcpFallback,
                    webProxy: request.CreateWebProxy(),
                    maxConnectionsPerServer: request.EffectiveMaxConnectionsPerServer);

                if (request.Port > 0) {
                    client.EndpointConfiguration.Port = request.Port;
                }
            }

            ApplyRequestConfiguration(client, request, ednsOptions);
            return client;
        }

        private static ClientX CreateClientForProvider(ResolveDnsRequest request, DnsEndpoint provider, EdnsOptions? ednsOptions) {
            var client = new ClientX(
                provider,
                request.DnsSelectionStrategy,
                request.TimeOutMilliseconds,
                request.UserAgent,
                request.HttpVersion,
                request.IgnoreCertificateErrors,
                enableCache: false,
                useTcpFallback: request.UseTcpFallback,
                webProxy: request.CreateWebProxy(),
                maxConnectionsPerServer: request.EffectiveMaxConnectionsPerServer);

            ApplyRequestConfiguration(client, request, ednsOptions);
            return client;
        }

        private static void ApplyRequestConfiguration(ClientX client, ResolveDnsRequest request, EdnsOptions? ednsOptions) {
            client.EndpointConfiguration.TimeOut = request.TimeOutMilliseconds;
            client.EndpointConfiguration.CheckingDisabled = request.CheckingDisabled;
            client.EndpointConfiguration.MaxConcurrency = request.EffectiveMaxConcurrency;
            if (ednsOptions != null) {
                client.EndpointConfiguration.EdnsOptions = ednsOptions;
            }
        }

        private static DnsResolverEndpoint[] ExpandMultiResolverEndpoints(ResolveDnsRequest request) {
            if (request.ResolverEndpoints.Length > 0) {
                var endpoints = EndpointParser.TryParseMany(request.ResolverEndpoints, out var errors);
                if (errors.Count > 0) {
                    throw new ArgumentException(string.Join("; ", errors), nameof(request.ResolverEndpoints));
                }

                return endpoints;
            }

            if (request.ResolverDnsProviders.Length > 0) {
                return request.ResolverDnsProviders
                    .SelectMany(DnsResolverEndpointFactory.From)
                    .ToArray();
            }

            if (request.DnsProviders.Length > 1) {
                return request.DnsProviders
                    .SelectMany(DnsResolverEndpointFactory.From)
                    .ToArray();
            }

            return Array.Empty<DnsResolverEndpoint>();
        }

        private static List<string> GetValidatedServers(ResolveDnsRequest request) {
            var invalidServers = new List<string>();
            var validServers = new List<string>();

            foreach (var serverEntry in request.Servers) {
                string trimmed = serverEntry?.Trim() ?? string.Empty;
                if (IsValidServerName(trimmed)) {
                    validServers.Add(trimmed);
                } else {
                    invalidServers.Add(serverEntry ?? string.Empty);
                }
            }

            if (invalidServers.Count > 0) {
                throw new ArgumentException($"Malformed server address(es): {string.Join(", ", invalidServers)}.", nameof(request.Servers));
            }

            if (validServers.Count == 0) {
                throw new ArgumentException("At least one valid server must be specified.", nameof(request.Servers));
            }

            return validServers.Distinct().ToList();
        }

        private static bool IsValidServerName(string value) {
            if (string.IsNullOrWhiteSpace(value)) {
                return false;
            }

            return IPAddress.TryParse(value, out _) || Uri.CheckHostName(value) != UriHostNameType.Unknown;
        }

        internal static Uri CreateServerBaseUri(string serverName, DnsRequestFormat requestFormat, int portOverride = 0) {
            var builder = new UriBuilder(Uri.UriSchemeHttps, serverName) {
                Path = GetServerRequestPath(serverName, requestFormat)
            };

            int port = portOverride > 0 ? portOverride : 443;
            if (port != 443) {
                builder.Port = port;
            }

            return builder.Uri;
        }

        private static bool UsesExplicitServerBaseUri(DnsRequestFormat requestFormat) {
            return requestFormat is
                DnsRequestFormat.DnsOverHttps or
                DnsRequestFormat.DnsOverHttpsJSON or
                DnsRequestFormat.DnsOverHttpsPOST or
                DnsRequestFormat.DnsOverHttpsWirePost or
                DnsRequestFormat.DnsOverHttpsJSONPOST or
                DnsRequestFormat.DnsOverHttp2 or
                DnsRequestFormat.DnsOverHttp3 or
                DnsRequestFormat.ObliviousDnsOverHttps or
                DnsRequestFormat.DnsOverGrpc;
        }

        private static string GetServerRequestPath(string serverName, DnsRequestFormat requestFormat) {
            if (requestFormat is DnsRequestFormat.DnsOverHttpsJSON or DnsRequestFormat.DnsOverHttpsJSONPOST) {
                if (string.Equals(serverName, "dns.google", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(serverName, "8.8.8.8", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(serverName, "8.8.4.4", StringComparison.OrdinalIgnoreCase)) {
                    return "/resolve";
                }
            }

            return "/dns-query";
        }

        private static void Shuffle(List<string> values) {
            var random = new Random();
            for (int i = values.Count - 1; i > 0; i--) {
                int j = random.Next(i + 1);
                (values[i], values[j]) = (values[j], values[i]);
            }
        }
    }
}
