name: Test .NET

on:
    push:
        branches:
            - main
        paths-ignore:
            - '*.md'
            - 'Docs/**'
            - 'Examples/**'
            - '.gitignore'
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    DOTNET_VERSION: '8.x'
    BUILD_CONFIGURATION: 'Release'

jobs:
    test-windows:
        name: 'Windows'
        runs-on: windows-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore DnsClientX.sln

            - name: Build solution
              run: dotnet build DnsClientX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

            - name: Run tests
              run: dotnet test DnsClientX.Tests/DnsClientX.Tests.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --framework net8.0 --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"
              env:
                  DNSCLIENTX_DEBUG_SYSTEMDNS: '1'

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-results-windows
                  path: '**/*.trx'

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-reports-windows
                  path: '**/coverage.cobertura.xml'

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  files: '**/coverage.cobertura.xml'

    test-ubuntu:
        name: 'Ubuntu'
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore DnsClientX.sln

            - name: Build solution
              run: dotnet build DnsClientX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

            - name: Run tests
              run: dotnet test DnsClientX.Tests/DnsClientX.Tests.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --framework net8.0 --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"
              env:
                  DNSCLIENTX_DEBUG_SYSTEMDNS: '1'

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-results-ubuntu
                  path: '**/*.trx'

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-reports-ubuntu
                  path: '**/coverage.cobertura.xml'

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  files: '**/coverage.cobertura.xml'

    test-macos:
        name: 'macOS'
        runs-on: macos-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore DnsClientX.sln

            - name: Build solution
              run: dotnet build DnsClientX.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

            - name: Run tests
              run: dotnet test DnsClientX.Tests/DnsClientX.Tests.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --framework net8.0 --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage"
              env:
                  DNSCLIENTX_DEBUG_SYSTEMDNS: '1'

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-results-macos
                  path: '**/*.trx'

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-reports-macos
                  path: '**/coverage.cobertura.xml'

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  files: '**/coverage.cobertura.xml'

